[package]
name = "identity-server"
version = "0.1.0"
authors = ["Markus Wiegand <mail@morphy2k.dev>"]
edition = "2021"
rust-version = "1.57"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["jemalloc"]

jemalloc = ["jemallocator"]

[dependencies]
jemallocator = { version = "0.3", optional = true }
tokio = { version = "1", features = ["full"] }
warp = { version = "0.3", default-features = false }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }
mongodb = { version = "2.1.0-beta", features = ["bson-chrono-0_4"] }
futures = { version = "0.3", default-features = false, features = [
    "async-await",
] }
argon2 = "0.3"
aes-gcm-siv = "0.10"
rand = { version = "0.8", features = ["std"] }
base64 = "0.13"
jsonwebtoken = "7"
passwords = "3"
envy = "0.4"
dotenv = "0.15"
log = "0.4"
env_logger = "0.9"
thiserror = "1"

[profile.release]
lto = true
opt-level = 3
debug = false
